# fly.toml app configuration file generated for frp-flyapp-3iwabq on 2025-01-02T06:31:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frp-flyapp-3iwabq'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
